name: Build Executable

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  # Build for Windows
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Latest stable python3 version

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build Windows Executable
        run: |
          pyinstaller --onefile Diagnostic_DownLoad.py
          mv dist/Diagnostic_DownLoad.exe ./  # Move executable to root for easy access

      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-Diagnostic_DownLoad
          path: Diagnostic_DownLoad.exe
